In [1]:
import numpy as np

In [2]:
array = np.random.randint(1, 21, size=20)

In [3]:
print(array)

[10  9  5 12  2  9 12  6 19  7 16 18  8 12  9 17 20 10 14 10]


In [12]:
print(array[5:][:-5])

[ 9 12  6 19  7 16 18  8 12  9]


In [13]:
print(array[5:-5])

[ 9 12  6 19  7 16 18  8 12  9]
